### ISSUE TITLE
MuHiSSE error

### ISSUE THREAD

**Issue by ethanfulwood** [thej022214/hisse#25]
Hello, I have been trying to run MuHiSSE on a set of data that includes a tree with fossils, and am getting this error:

Error in if (x[i] == 0 & y[i] == 0) { : 
  missing value where TRUE/FALSE needed

Which I take to mean that "NA" has been called instead of a True/False?

I tried manually defining the functions from the GitHub code and it seems to identify an issue with OrganizeData, although I'm having trouble understanding what:

Error in if (x[i] == 0 & y[i] == 0) { : 
  missing value where TRUE/FALSE needed
Called from: OrganizeData(data = data.new, phy = phy, f = f, hidden.states = hidden.states, 
    includes.fossils = includes.fossils)

This is the code that I've called:

##################
f <- GetFossils(analytree, psi=0.05)
fbd.tree <- ProcessSimSample(analytree, f)

states<-data.frame(species=topographies$species, dne=as.numeric(topographies$dne_cat), dne.1=as.numeric(topographies$dne_cat))
states.trans<-states

for(i in 1:Ntip(analytree)){
  if(states[i,2] == 1){ 
    states.trans[i,2] = 0 
    states.trans[i,3] = 0
  }
  if(states[i,2] == 2){
    states.trans[i,2] = 0
    states.trans[i,3] = 1
  }
  if(states[i,2] == 3){ 
    states.trans[i,2] = 1 
    states.trans[i,3] = 0
  }
  if(states[i,2] == 4){
    states.trans[i,2] = 1
    states.trans[i,3] = 1
  }
}

trans.rate <- TransMatMakerMuHiSSE(hidden.traits = 1)

turnover <- c(1,2,3,4, 5, 6, 7, 8)
extinction.fraction <- rep(1, 8) 
f = rep(1, 8)

pp <- MuHiSSE(phy=fbd.tree$phy, data=states.trans, f=f, turnover=turnover, eps=extinction.fraction, hidden.states = TRUE, trans.rate=trans.rate, k.samples=fbd.tree$k.samples, includes.fossils=TRUE)

**Comment by mpmeurville** [comment]
Hi Ethan, I have the same issue with the hisse function, did you find out how to solve it?

**Comment by thej022214** [comment]
Oh, I missed this. I have something to do this morning, but I will take a look this afternoon and get back to you both.

**Comment by thej022214** [comment]
So, actually it appears that one line in your code is what is triggering the error. You have

f=rep(1,8).

But it should be:

f=rep(1,4).

You only put down the sampling proportion for the observed states (because you don't know the sampling proportion for the hidden states. 

Here's some code that shows that it does in fact work (sorry, it's a bit much):

library(hisse)
library(diversitree)
pars <- c(.1,  .15,  .2, .1, # lambda 1, 2, 3, 4
.03, .045, .06, 0.03, # mu 1, 2, 3, 4
.05, .05, .00,        # q12, q13, q14
.05, .00, .05,     # q21, q23, q24
.05, .00, .05,     # q31, q32, q34
.00, .05, .05)
set.seed(2)
phy <- NULL
while( is.null( phy ) ){
    phy <- tree.musse(pars, 30, x0=1, include.extinct=TRUE)
}
#f <- hisse:::GetFossils(phy, psi=0.01)
#h <- history.from.sim.discrete(phy, 1:4)
#plot(h, phy)
k.samples <- data.frame(taxon1="sp20", taxon2="sp37", timefrompresent=8.54554, state1=0, state2=1, stringsAsFactors=FALSE)

phy.k <- hisse:::AddKNodes(phy, k.samples)
fix.type <- hisse:::GetKSampleMRCA(phy.k, k.samples)
nb.tip <- Ntip(phy.k)
nb.node <- phy.k$Nnode
gen <- hisse:::FindGenerations(phy.k)

states <- phy$tip.state
states <- data.frame(phy$tip.state, phy$tip.state,
row.names=names(phy$tip.state))
states <- states[phy$tip.label,]
states.trans <- states
for(i in 1:Ntip(phy)){
    if(states[i,1] == 1){
        states.trans[i,1] = 0
        states.trans[i,2] = 0
    }
    if(states[i,1] == 2){
        states.trans[i,1] = 0
        states.trans[i,2] = 1
    }
    if(states[i,1] == 3){
        states.trans[i,1] = 1
        states.trans[i,2] = 0
    }
    if(states[i,1] == 4){
        states.trans[i,1] = 1
        states.trans[i,2] = 1
    }
}

data <- data.frame(taxon=names(phy$tip.state), states.trans[,1], states.trans[,2], stringsAsFactors=FALSE)
data <- hisse:::AddKData(data, k.samples, muhisse=TRUE)

turnover <- c(1,2,3,4, 5, 6, 7, 8)
extinction.fraction <- rep(1, 8)
f = rep(1, 4)
trans.rate <- TransMatMakerMuHiSSE(hidden.traits = 1)

pp <- MuHiSSE(phy=phy.k, data=data, f=f, turnover=turnover, eps=extinction.fraction, hidden.states = TRUE, trans.rate=trans.rate, k.samples=NULL, includes.fossils=TRUE)

**Comment by thej022214** [comment]
There might be other issues with this function, so please let me know if something else pops up along the way.

**Comment by thej022214** [comment]
If things pop up. Just let me know.
